### ISSUE TITLE
Add option to output color settings as RGB

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/userstyles#13]
http://forum.userstyles.org/discussion/40594/get-rgb-color-values-from-user-selected-color-setting

Perhaps by append "-rgb" to the install key?

**Comment by JasonBarnabe** [comment]
If you have an install key for `mycolor`, if you use `mycolor-rgb` in your code, it will output in the format `0, 0, 0`.

**Comment by Mottie** [comment]
Because it isn't completely clear, it would be nice to expand the [documentation page](https://userstyles.org/help/coding) by adding an example of this usage to the placeholder section. 

For example

```css
.highlight {
  border: /*[[mycolor]]*/ !important;
  background: rgba(/*[[mycolor-rgb]]*/, .8) !important;
  color: #fff !important;
}
```

With the color set to `#000000`, the css becomes:

```css
.highlight {
  border: #000000 !important;
  background: rgba(0, 0, 0, .8) !important;
  color: #fff !important;
}
```
